const fs = require('fs');
/**
 * Loads environment variables which contain git information as well as the remaining time
 * off a file that is generated by the App Service.
 * 
 * If you're not playing with Try App Service, this can be safely deleted.
 */
module.exports = function() {
    return fs.readFileSync(`${__dirname}/template.html`, 'utf8')
        .replace(
            '{ envVars }',
            `let env = ` +
            JSON.stringify({
                gitUrl: process.env['APPSETTING_SITE_GIT_URL'],
                bashGitUrl: process.env['APPSETTING_SITE_BASH_GIT_URL'],
                expiry: JSON.parse(fs.readFileSync('metadata.json', 'utf8')).expiryTime,
                host: process.env['HTTP_HOST']
            })
        );
}